### ISSUE TITLE
登录系统有问题

### ISSUE THREAD

**Issue by jinhongyii** [MXWXZ/sjtu-automata#1]
![image](https://user-images.githubusercontent.com/44201588/50285201-72d9e980-0496-11e9-98b4-3b70bf601fa0.png)

**Comment by MXWXZ** [comment]
嗯目前没有开放选课造成的，为了防止出现问题所有返回值都是白名单处理，因为第二轮选课显示的信息不同所以会报错，不影响使用。
不过下一版本会提示选课未开放而不是报错。

**Comment by jinhongyii** [comment]
不是说如果没有开放选课将会自动等待并定时刷新吗？

**Comment by MXWXZ** [comment]
这是为了避免出现其他问题和不可控的情况发生，只要发生错误就会自动退出。
2天后发布的0.1.2会修复的。
