### ISSUE TITLE
256位课程码每次复制不同，会影响程序进行选课吗？

### ISSUE THREAD

**Issue by xiahongchi** [MXWXZ/sjtu-automata#18]
256位课程码每次复制不同，会影响程序进行选课吗？

**Comment by MXWXZ** [comment]
不会，系统设计就是这样的，多次登录课程码不同，会有过期时间但是都对应的是一个课程。

**Comment by xiahongchi** [comment]
为什么这几天输入autoelect 和课程号之后会出现“远程主机强制关闭了现有的连接”，之前还不会的，发生肾么事了？
