### ISSUE TITLE
命令可以有缩写

### ISSUE THREAD

**Issue by jinhongyii** [MXWXZ/sjtu-automata#2]
抢课时候要打的命令太长，比如gridModule$ctl02$radioButton，无法自动补全，影响速度 
建议在ls列出一些选项之后可以列出一些缩写，比如首字母，或者顺序的数字之类的，要cd或者elect直接打缩写就可以

**Comment by MXWXZ** [comment]
因为设计初衷就是在海选是记录下命令然后抢选可以直接跑，因为交互模式在抢选时的优势并不大，主要是为了方便查看指令的。
因为操作安全性是第一优先级，因此CLI模式可能不会支持简写，不过交互模式以后可以添加自动补全等功能。
