### ISSUE TITLE
报错PIL.UnidentifiedImageError: cannot identify image file 'captcha.jpeg'

### ISSUE THREAD

**Issue by treerobin06** [MXWXZ/sjtu-automata#25]
<img width="717" alt="image" src="https://github.com/MXWXZ/sjtu-automata/assets/126230403/c0c59ea8-c0f7-4dc6-b0a0-b1715d5296f9">
显示此报错 该如何解决

**Comment by G-dab** [comment]
我也遇到了这个问题，不知道怎么解决

**Comment by BRsjtu** [comment]
似乎是登录界面更新了，用户无法直接通过验证码url打开图片，无法获取查看权限，或许这个问题要通过google自动化脚本解决？

**Comment by proItheus** [comment]
jaccount系统更新了检测，现在需要加上合适的`Referer`请求头才能请求到验证码。我已经提了一个PR，merge之前可以先用我的[fork](https://github.com/proItheus/sjtu-automata)
