### ISSUE TITLE
海选阶段通选课、体育课显示“unknown error”

### ISSUE THREAD

**Issue by MinstrelsyXia** [MXWXZ/sjtu-automata#28]
![image](https://github.com/MXWXZ/sjtu-automata/assets/129087396/dc734e80-575b-445f-9412-4c5745b74c26)

**Comment by MXWXZ** [comment]
目前已毕业，没法测试咯……欢迎提交pr

**Comment by proItheus** [comment]
我这边可以正常使用。你是不是在挂着选课的同时在别的地方登录了`i.sjtu.edu.cn`? 那样的话选课程序的登录会被挤掉。
