### ISSUE TITLE
教务系统更新

### ISSUE THREAD

**Issue by jinhongyii** [MXWXZ/sjtu-automata#3]
马上教务处要换新系统了，希望下一个新版本可以针对新系统进行更新。
![image](https://user-images.githubusercontent.com/44201588/50419736-58748700-086d-11e9-9791-29a243d3bb31.png)

**Comment by MXWXZ** [comment]
会支持的，目前来看新版本写的还是可以，协议较为容易，至少可以提速80%。

**Comment by MXWXZ** [comment]
@jinhongyii  v0.2.0发布，改版后efficiency非常NB，欢迎测试~
