### ISSUE TITLE
疑似在输入账号密码后陷入死循环

### ISSUE THREAD

**Issue by Hydr0pon1c** [MXWXZ/sjtu-automata#32]
![微信图片_20241216232129](https://github.com/user-attachments/assets/806efa41-3377-45f7-abe4-024121539a6e)
windows是要额外下载验证码识别相关的软件吗？

**Comment by Hydr0pon1c** [comment]
这个界面在输入密码并按下回车后就一直没反应了

**Comment by MXWXZ** [comment]
应该是和 #29 #30 类似的问题，可以试下master分支的版本，pip上的没有更新
