### ISSUE TITLE
新学期教学班名称不是六位了

### ISSUE THREAD

**Issue by Neight99** [MXWXZ/sjtu-automata#5]
新学期教学班名称不是六位了，而是各个课程内进行编号了。希望能进行跟进

<img width="1182" alt="Snipaste_2019-05-27_14-26-57" src="https://user-images.githubusercontent.com/32681608/58399678-8a438100-808b-11e9-9a9c-a1b91548843d.png">

**Comment by Neight99** [comment]
然后目前在mac测试除了因为不支持新版教学班之外没遇到别的问题owo

**Comment by MXWXZ** [comment]
已经更新，欢迎测试BUG

**Comment by Neight99** [comment]
测试过了，在macOS Mojave 10.14.5 (18F132) 下能正常运行无BUG，多谢owo
