### ISSUE TITLE
第二轮使用脚本抢课后状态为“待筛选”

### ISSUE THREAD

**Issue by chenhs1641** [MXWXZ/sjtu-automata#7]
<img width="385" alt="捕获" src="https://user-images.githubusercontent.com/51705930/59288023-66945380-8ca5-11e9-8d46-a3fcb17fbe06.PNG">
<img width="931" alt="捕获2" src="https://user-images.githubusercontent.com/51705930/59288024-672cea00-8ca5-11e9-8200-19d34bb41418.PNG">

**Comment by MXWXZ** [comment]
教务系统昨天更新了,0.3.2已修复.
