### ISSUE TITLE
第三轮选课无法使用

### ISSUE THREAD

**Issue by Zirconium-9** [MXWXZ/sjtu-automata#8]
![image](https://user-images.githubusercontent.com/30790455/64506066-cdf38b00-d308-11e9-9496-65554aad20de.png)
登陆后停留在starting thread阶段，即使是有空的课也无法选

**Comment by MXWXZ** [comment]
选课系统有更新，晚上修复

**Comment by Neight99** [comment]
啥时候更新鸭，哭力

**Comment by MXWXZ** [comment]
emmmm这次更新比较制杖校验了很多东西，下次海选的时候会重构一次，暂时不可用。

**Comment by kubev** [comment]
跪求大神更新OrzOrzOrzOrzOrz
0.3.2版本现在也是不能用的，[Info] Starting thread...之后就停止了

**Comment by MXWXZ** [comment]
第三轮选课可用临时版本更新
